_target_: rtr_async_sys.models.reactive_diffusion_policy.policy.kinedex_image_policy.DiffusionUnetImagePolicy

shape_meta: &shape_meta
  # acceptable types: rgb, low_dim
  obs:
    left_wrist_img:
      shape: [3, 240, 320]
      type: rgb
    left_robot_tcp_pose:
      shape: [9]
      type: low_dim
    left_robot_gripper_width:
      shape: [1]
      type: low_dim
    left_gripper1_marker_offset_emb:
      shape: [ 15 ]  # the raw dimension is (63*2), we use PCA to reduce the dimension to 15
      type: low_dim
  action:
    shape: [25] # (3+6+1+15) (x, y, z, 6d rotation, gripper_width, tactile_emb_15d)

noise_scheduler:
  _target_: diffusers.schedulers.scheduling_ddim.DDIMScheduler
  num_train_timesteps: 100
  beta_start: 0.0001
  beta_end: 0.02
  # beta_schedule is important
  # this is the best we found
  beta_schedule: squaredcos_cap_v2
  clip_sample: True
  set_alpha_to_one: True
  steps_offset: 0
  prediction_type: epsilon # or sample

obs_encoder:
  _target_: rtr_async_sys.models.reactive_diffusion_policy.model.vision.multi_image_obs_encoder.MultiImageObsEncoder
  shape_meta: *shape_meta
  rgb_model:
    _target_: rtr_async_sys.models.reactive_diffusion_policy.model.vision.model_getter.get_resnet
    name: resnet18
    weights: null
  resize_shape: [240, 320]
  random_transforms:
    - type: RandomCrop
      ratio: 0.90
  use_group_norm: True
  share_rgb_model: False
  imagenet_norm: True


horizon: 16
n_action_steps: 8 #${eval:'${n_action_steps}+${n_latency_steps}'}
n_obs_steps: 2
num_inference_steps: 100
obs_as_global_cond: True
# crop_shape: null
diffusion_step_embed_dim: 128
down_dims: [512, 1024, 2048]
kernel_size: 5
n_groups: 8
cond_predict_scale: True

