cuda_visible_devices: "0"
log_dir: "./outputs/tactile_vae"
ckpt_dir: "./outputs/tactile_vae/checkpoints"
data_path: "data/tactile_data/dish_vase_/tacwm_samples"
batch_size: 64
val_batch_size: 8
lr: 1e-3
epochs: 500
beta: 1.0
device: "cuda"
vae_decode_mode: "condition"
out_H: 36
out_W: 20
base_ch: 16
conv_layers_normal: 2
conv_layers_tangent: 2
load_ckpt_path: "data/checkpoints/tactile_vae_condition/best_model.pth"
data_norm_config: "src/rtr_async_sys/models/Tactile_Generation_Policy/tactile_generation_policy/config/dataset/data_distribution.yaml"
