_target_: rtr_async_sys.executor.async_nonservo_executor.AsyncNonServoExecutor

defaults:
  - env: dp_dataset_env
  - _self_
  
ctrl_bind: tcp://*:10010
sched_bind: tcp://*:10011
max_merge_len: 1
servo_mode: False