_target_: rtr_async_sys.executor.sync_nonservo_executor.SyncNonServoExecutor

defaults:
  - env: dp_dataset_env
  - _self_
# env: src/rtr_async_sys/configs/env/dp_dataset_env.yaml
ctrl_bind: tcp://*:10010
sched_bind: tcp://*:10011