_target_: rtr_async_sys.model_wrapper.ldp_with_block_vae_model_wrapper.LdpModelWrapper

defaults:
  - model: rdp/ldp_with_block_vae
# model: src/rtr_async_sys/configs/model/rdp/rdp_abs.yaml
ckpt_path: null
device: cuda:0
return_raw_action: False
use_relative_action: False
compress_obs: False
need_refine: False
return_latent_action: False
block_reuse: False
reuse_latent_num: 3
reuse_action_num: 12
openloop_eval: False

shape_meta: &shape_meta
  # acceptable types: rgb, low_dim
  obs:
    left_wrist_img:
      shape: [3, 240, 320]
      type: rgb
    left_robot_tcp_pose:
      shape: [9]
      type: low_dim
    left_robot_gripper_width:
      shape: [1]
      type: low_dim
    left_gripper1_marker_offset_emb:
      shape: [ 15 ]  # the raw dimension is (63*2), we use PCA to reduce the dimension to 15
      type: low_dim
  extended_obs: # for the AT RNN decoder of the latent diffusion policy
    left_gripper1_marker_offset_emb:
      shape: [ 15 ]  # the raw dimension is (63*2), we use PCA to reduce the dimension to 15
      type: low_dim
  action:
    shape: [10] # (3+6+1) (x, y, z, 6d rotation, gripper_width)