_target_: rtr_async_sys.model_wrapper.rdp_block_vae_model_wrapper.RdpBlockVaeModelWrapper

# model: src/rtr_async_sys/configs/model/rdp/dp.yaml
defaults:
  - model: rdp/rdp_block_vae
  - _self_

ckpt_path: data/checkpoints/rdp_vae/latest.ckpt
device: cuda:0
return_raw_action: False
compress_obs: False
