_target_: rtr_async_sys.controller.async_controller.AsyncController

exec_endpoint: tcp://127.0.0.1:10010
user_bind: tcp://*:10020
sched_bind: tcp://*:10021
control_hz: 10
control_horizon: 10
warm_up_step: 0